### ISSUE TITLE
About Menu target attribute

### ISSUE THREAD

**Issue by kkpoon** [react-mdl/react-mdl#269]
it seems that the target attribute require dom ID to anchor with the button is not a good idea in React world. It is so difficult to get an ID for the reused components.

https://tleunen.github.io/react-mdl/components/menu/

**Comment by tleunen** [comment]
I fully agree with that, but that's how the original MDL works unfortunately.
I don't see it changing before our v2 version though.. Unless someone has a good idea how to resolve it in v1?

**Comment by tleunen** [comment]
@kkpoon - What do you think of having the `target` props accepting a string (current behavior) or an element? If it's an element, the Menu will display the element and automatically attach the menu to it.

**Comment by darkyen** [comment]
@tl

**Comment by lsemerini** [comment]
@tleunen 

You mean something like this?

`<div style={{position: 'relative'}}>
			<IconButton name="more_vert" id="demo-menu-lower-right" />
			<Menu target={
				<ComponentX />
			} align="right">
				<MenuItem>Some Action</MenuItem>
				<MenuItem>Another Action</MenuItem>
				<MenuItem disabled>Disabled Action</MenuItem>
				<MenuItem>Yet Another Action</MenuItem>
			</Menu>
		</div>` 

That will render ComponentX with the menu attached to it? 

If that's the case, +1 for this, i need it to work for my project.

**Comment by tleunen** [comment]
Yes I meant that. I'm still not sure about it since it's not something common in a React world :)
