### ISSUE TITLE
On 1.7.1 Tabs won't get upgraded automatically

### ISSUE THREAD

**Issue by igorsantos07** [react-mdl/react-mdl#394]
Using `<MDLComponent><Tabs>[...]</Tabs></MDLComponent>` works :B

**Comment by tleunen** [comment]
Are you talking about `Tabs` in the `HeaderTabs`, or the generic `Tabs` component?

Because [these tabs](https://tleunen.github.io/react-mdl/components/tabs/) work fine, I can see the ripple for example, same for the `HeaderTabs` in the example with the 6 tabs.

What's your issue exactly?

**Comment by igorsantos07** [comment]
[These tabs](http://codepen.io/igorsantos07/pen/wzrobZ?editors=0010) do not display ripples :)
This codepen is based on the example's code - I just doubled the Tabs, so I could create one that was wrapped by MDLComponent to display my findings.

**Comment by tleunen** [comment]
Hmm weird, it looks like it doesn't get upgraded. I'll investigate

**Comment by igorsantos07** [comment]
As mentioned on #380, I'm bringing here the [codepen](http://codepen.io/igorsantos07/pen/pEgNrK?&editors=001) displaying HeaderTabs that seems to be upgraded (they do have the colored underline) but have no ripple effect

**Comment by Place1** [comment]
Can confirm i'm getting this issue as well. Something i noticed was that it worked with the official MDL js/css. I'm porting a react UI that used MDL without this library. I had the Tabs all working and then my last step was to swap out the MDL css/js from google with the one from this library and then it broke.

not sure if that's any help but i thought i'd let you know :D

**Comment by vitalets** [comment]
Also can confirm this issue. Would appreciate the fix..

**Comment by tleunen** [comment]
Thanks for the info @Place1.
I'm very busy still for a few days so I won't be able to take a closer look and find a fix. So any help is welcome

**Comment by gabrielbull** [comment]
Me too, having the same issue.

**Comment by DirtyHairy** [comment]
The heart of this issue is the component upgrade not handling functional components correctly. In addition, ripple requires `upgradeElements` (not the plural :smirk:) instead of `upgradeElement` to be called on the element. Both issues never show up on the doc pages as `upgradeElements` is called on the whole page during bootstrap there.

The above PR fixes these issues.

**Comment by tleunen** [comment]
Good catch @DirtyHairy! I'll take a look at the PR tomorrow.

**Comment by DirtyHairy** [comment]
Thanks alot, @tleunen :smile: I'm in the progress of collecting similar ripple effect fixes (`updateElements` vs `upgradeElement`) as we stumble upon them, but I'll keep these in a branch for a later pull request.

**Comment by Place1** [comment]
Yeah good stuff!

**Comment by marcelpanse** [comment]
I also need this, can the PR be merged?

**Comment by tleunen** [comment]
Merged and released as 1.8.0
