### ISSUE TITLE
Importing Drawer with another name breaks the Drawer

### ISSUE THREAD

**Issue by mattmichler** [react-mdl/react-mdl#430]
I am creating a component named Drawer in my app that imports the react-mdl Drawer component so I tried to do:
`import { Drawer as mdlDrawer } from 'react-mdl'`

Importing and rendering happened but not properly. I think what happens is the material.js  that hooks up drawers couldn't find the element, but that's a guess. What I've done as a work around is named my component Drawer_ and just import Drawer from react-mdl the typical way.

**Comment by kradio3** [comment]
I cannot reproduce it with react 1.9.0 [see Gist](https://gist.github.com/kradio3/c4a7dea4ff6e1d613d4aeea7f4772388)

**Comment by mattmichler** [comment]
I just forgot JSX treats lowercase tags as html... embarrassing.
