### ISSUE TITLE
Safari-only bug: "Attempting to change value of a readonly property"

### ISSUE THREAD

**Issue by endash** [react-mdl/react-mdl#434]
As a consequence of the commit from a few days ago (b8dfeb), react-mdl is now broken in Safari, at least in version 9.1.2.

It explodes on https://github.com/react-mdl/react-mdl/blob/master/src/utils/mdlUpgrade.js#L24

**Comment by DirtyHairy** [comment]
I just noticed the same on some stock Android browsers --- me culpa, this didn't show up in my tests :disappointed: . I have put up PR #437 with a fix.

**Comment by endash** [comment]
Thank you 👍🏻
