### ISSUE TITLE
Toggle in Layout changes color depending on the width.

### ISSUE THREAD

**Issue by tkreis** [react-mdl/react-mdl#439]
At 1024px the menu toggle-button's font gets changed to black. 

This could cause an expected bugs when a developer doesn't test different layouts and it changes to black unexpected. 

Link to the component: https://react-mdl.github.io/react-mdl/components/layout/
Here are two screenshots highlighting the problem:
![screen shot 2016-11-28 at 11 03 51](https://cloud.githubusercontent.com/assets/2585243/20664228/92569b74-b55a-11e6-9e1e-d1fdd760e313.png)

![screen shot 2016-11-28 at 11 04 01](https://cloud.githubusercontent.com/assets/2585243/20664227/92549a0e-b55a-11e6-9831-eade9b368ea5.png)

**Comment by tleunen** [comment]
Looks like it's an issue in the Material Design Lite project itself. Can you report the issue there please?

See these lines:
Default color: 
https://github.com/google/material-design-lite/blob/mdl-1.x/src/layout/_layout.scss#L197

Hardcoded to black under the media query:
https://github.com/google/material-design-lite/blob/mdl-1.x/src/layout/_layout.scss#L213
