### ISSUE TITLE
Using material components web

### ISSUE THREAD

**Issue by dannyphung** [react-mdl/react-mdl#450]
As on MDL repo:
>Material Design Lite is now in limited support, with development having moved to the[ Material Components for the web](https://github.com/material-components/material-components-web) repository.

So will we update React-mdl to use new script?

**Comment by tleunen** [comment]
@idancali What's your call on this?

Should we update/change name (react-mdc?) of this package? Do you prefer creating a brand new one for the new implementation, or keep react-mdl for the new implementation.

**Comment by idancali** [comment]
Hey guys @dannyphung @tleunen 

MDL as a brand is being sunsetted as far as I can tell. It would not make much sense for us to keep onto the MDL brand if they're moving away from it.

I think it might make more sense to create a brand new one  from scratch. 
I'm thinking something like React-Material would make more sense.

I would love to get the @react-material org but it seems taken. Not much activity there. I wonder if GitHub would be willing to let us have it to transfer @react-mdl over.

Thoughts?

**Comment by tleunen** [comment]
It would be awesome, indeed. 
Try contacting github, and the author of the org if you can find an email. I'm sure there won't be any problem.

**Comment by idancali** [comment]
I'm going to contact them. I did that before for other orgs and they were really cool about. I'll get back with more info once I hear back from them.

**Comment by idancali** [comment]
I've contacted them. I'll wait for a response and I'll keep you guys in the loop.

**Comment by idancali** [comment]
Hey guys, looks like GitHub thinks that the org is being used so we can't have it. We can go with something like @react-material-design perhaps.

Thoughts?

**Comment by tleunen** [comment]
The person who seems to own react-material is @lkarthee. I found his email from one of his commits. Wanna try sending him an email directly?

His email is his github username [at] gmail

**Comment by idancali** [comment]
great idea, I'll do that

**Comment by idancali** [comment]
@tleunen great news!

I got in touch with Kartheek @lkarthee and he is an absolutely outstanding person! Thanks so much for being so amazing about this @lkarthee 

He transferred the ownership of @react-material to me so I'm now the owner of that org. I'll connect with you separately, @tleunen to talk about next steps.

Once again, many thanks @lkarthee, I really appreciate it, all the best with your startup!

**Comment by dannyphung** [comment]
Guys, that's great!
I will keep in touch and closing this issue now.

**Comment by tleunen** [comment]
It might also be a good idea to sync with @haoxins. He created https://github.com/haoxins/react-mdc

**Comment by haoxins** [comment]
Hi, guys! That is so great! I can transfer react-mdc on npm. Just give me some hours    , when I get my computer. 👏

发自我的 iPhone

**Comment by stunaz** [comment]
Hi guys,
what's new with this?
Maybe you guys can team up?
cc @tleunen @haoxins @idancali @kradio3 @Hardtack

**Comment by codekiln** [comment]
This is confusing!

**Comment by tleunen** [comment]
React-MDL will probably not update. Unless someone else wants to take the lead and build something.
