### ISSUE TITLE
Library request on CDNJS

### ISSUE THREAD

**Issue by extend1994** [react-mdl/react-mdl#479]
Hi!
There is a library request cdnjs/cdnjs#10759 and I am a member of CDNJS in charge of adding this library.
I want to confirm which files should CDNJS host to allow users to user it on the browser correctly.
I will add the files on npm.
They include all files under `extra/` directory after v0.11.1. But before v0.11.0 I am not sure what files should I add.

Could you please tell me if 

> all files under `extra/` directory after v0.11.1

is correct and what files should I add before v0.11.0?

Thanks!

**Comment by tleunen** [comment]
Hi @extend1994,

I'm not sure it's interesting to have all versions on CDNJS, especially the ones before 1.0.

Also, this library is getting deprecated, if not already, in favor of [material-components-web](https://github.com/material-components/material-components-web), so I'd say that only the latest version could be on cdnjs. There's a very low chance we release any new versions here.

**Comment by extend1994** [comment]
@tleunen Thanks for your response!
@PeterDaveHello Should we host the library in this case?

**Comment by extend1994** [comment]
I saw there are people using this library on https://www.npmjs.com/package/react-mdl. So I still decide to add this library in https://github.com/cdnjs/cdnjs/pull/11878. Anyone need this library can use CDNJS service :) We are also adding material-components-web!
